services:
  - type: web
    name: anime-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8507552194:AAE9L2rlr2dg4ngv_gKImaQAypIohdktInI
      - key: PYTHON_VERSION
        value: 3.10.0
